# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::GraphViz; end
module Bpl::AST::Body::Label; end
module Bpl::Verification::EventMachine; end
module T::CompatibilityPatches::RecorderExtensions; end
